### ISSUE TITLE
Not finding the home key + CTRL key is not working.

### ISSUE THREAD

**Issue by ChizyPeasy** [amazeedaizee/CustomStreamLoader#3]
Hello! I am a french fellow who wanted to try the mod for fun, but sadly there is a problem, since i have an AZERTY keyboard there is no home key on my keyboard, even using the CTRL key isnt working, i don't know what to do, i was thinking if there was a wait to change the key to load the stream in NSO but i'm not sure about this.

**Comment by amazeedaizee** [comment]
Hello! Thanks for reporting on this. Since this issue talks more about the partner mod rather than the program itself, I have transferred your issue to the CustomStreamLoader repo instead.

To confirm, you can't use either Control key (or Command key if you're on Mac I'm assuming) when pressing the Stream button in the lower right corner to access your custom-made stream right?

Can you describe on what operating system you're playing this on, and more information about the keyboard your using? I know the key layout is in AZERTY, but is it a fullsize keyboard? A tenkeyless? Are you currently testing the mod on a laptop?

I heard that for some laptops (if you're using one), the Fn key + left arrow key can function as a home key, can you test that out and see if it works? (if applicable)

**Comment by ChizyPeasy** [comment]
I am not on a MAC and its still not working, im testing it right now and none of the commands i looked up online seems to activate the custom stream i did for NSO.. My keyboard does not have the ten keys on the right saldy.

**Comment by amazeedaizee** [comment]
If its alright, I'll need some more info about your current situation:
- Are you using the latest version of the game?
- Are you using the latest version of the mod?
- What version of Windows are you using?
- Since you are using Windows, there is an application that can bring up an on-screen keyboard. Please verify if you are using the latest version of both the game and the mod, and try to access the custom stream by clicking on the Home button of this keyboard at the Login/Caution screen.

**Comment by ChizyPeasy** [comment]
I am using the latest version of NSO since i bought it on stream.
I think i am on Windows 11.
I am using the 1.2.0 version of the steamaker since its the only one with an executable exe thingy.
I am using the latest version of the SteamLoader too.
And i did tried the virtual keyboard on my pc and it doesnt work.

**Comment by amazeedaizee** [comment]
Thanks for the quick response!

To verify, typing in the password in the beginning of every new game does work? 
And if you can, can you share the console output if you have it open while you were testing out the program?
In the BepInEx.cfg file in the config folder these options should be applied:
```
UnityLogListening = true      // in Logging.Console section
WriteUnityLog = true     // in Logging.Disk section
LogLevels = Fatal, Error, Warning, Message, Info       // for both Logging.Console and Logging.Disk
```
If it's not, apply these options with the values above in the config file, then do the actions you did before, close the game, then send me the LogOutput.log file in the BepInEx folder here.

Again, sorry for the inconvenience!

**Comment by ChizyPeasy** [comment]
It's not changing anything..
[LogOutput.log](https://github.com/user-attachments/files/18066154/LogOutput.log)

**Comment by amazeedaizee** [comment]
The console thing is only so that I can check the state of your game. From the file that you gave me, it doesn't seem like the CustomStreamLoader mod is even loaded into the game. For instance, here's what it would look like if this mod is loaded in the game:

```
...
[Info   :   BepInEx] Running under Unity v2022.3.22.8944612
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load  
[Info   :   BepInEx] Loading [Custom Stream Loader 1.0.0.1]
[Info   :Custom Stream Loader] A plugin to load in custom streams. Press the Home key on the Login/Caution screen to begin.
...
```
Can you double check if the mod is installed correctly?

**Comment by ChizyPeasy** [comment]
Weird, because the CustomStreamLoader is infact in the plugins files of  BepInEx....

**Comment by amazeedaizee** [comment]
In that case, you probably have to reinstall BepInEx in some way. You can either reinstall it manually or with a preconfigured version, and see if it works.

**Comment by ChizyPeasy** [comment]
Aaaand its still not working. .  And also this thing

![image](https://github.com/user-attachments/assets/0bc57c82-01e6-43c4-867d-e1289c3c8f6d)
![image](https://github.com/user-attachments/assets/6afc11bb-8db6-44c8-901e-dc1a12b9330d)

**Comment by amazeedaizee** [comment]
Can you send me a screenshot containing the contents of both the game files (NEEDY GIRL OVERDOSE, not what's in Windose_Data), and what's in the plugins folder?

Also just to be on the safe side, verify the game integrity in case any game files might be corrupted

**Comment by ChizyPeasy** [comment]
![image](https://github.com/user-attachments/assets/d8392ae3-c4bb-49f6-9386-d74d7f155bbf)
![image](https://github.com/user-attachments/assets/49e9abcc-5108-476c-8e37-c8f050612c7e)

**Comment by amazeedaizee** [comment]
If I can ask, how did you install BepInEx? Did you install it manually or did you install a preconfigured version? I'm asking because of the CoreCLR files there in the game files

**Comment by ChizyPeasy** [comment]
....preconfigured version, because idk how to do it manually...

**Comment by amazeedaizee** [comment]
That does seem pretty odd. I might have one thing that could work, though its not guarenteed.

First, back-up the Windose_Data folder and delete everything that's in the game folder. Then, verify integrity again on Steam.
(The Windose_Data folder contains your save data; backing it up ensures that your current progress isn't lost.)

Then, extract the contents from this zip into the game folder. It contains the newest version of BepInEx 5, already preconfigured with the current version of the game, and also has the CustomStreamLoader mod pre-installed. Note: this only works on x64 bit computers, if you have one that's x86, please let me know.

[BepInEx5.4.23.2_NGO.zip](https://github.com/user-attachments/files/18087064/BepInEx5.4.23.2_NGO.zip)


Then open the game and see if the mod is loaded into the game in the console.

**Comment by ChizyPeasy** [comment]
Now its working!! Thanks!!! Is it possible to add more mods or do i need to delete the previous one to make it work though?

**Comment by amazeedaizee** [comment]
You can add as many mods as you want in the plugins folder! Note that some mods are written for version 5.4.21 of BepInEx, so I can't guarantee that all mods will work. Still, happy that the stream loader is finally working!

I'll mark this issue as completed since the mod finally works in the game.
